name: Piggymetrics.Account-Service

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Docker Build
      run: docker build -t ghcr.io/srivatsamarichi/piggymetrics:${{ github.run_number }} -f account-service/Dockerfile .
    
    - name: Docker login
      run: |
        echo "${{ secrets.GCRACCESSTOKEN }}" | docker login ghcr.io/srivatsamarichi/piggymetrics -u srivatsamarichi -p ${{ secrets.CR_PAT }}
    
    - name: Docker push
      run: |
        docker push ghcr.io/srivatsamarichi/piggymetrics:${{ github.run_number }}
