name: Piggymetrics.Turbine-stream-service

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
        registry: ghcr.io
        #repository: srivatsamarichi
        tags: piggymetrics-turbine-stream-service:${{ github.run_number }}
        dockerfile: turbine-stream-service/Dockerfile
        #labels: turbine-stream-service
        push: true
    
    #- name: Docker Build
    #  run: docker build -t ghcr.io/srivatsamarichi/piggymetrics-turbine-stream-service:${{ github.run_number }} -f turbine-stream-service/Dockerfile .
    
    #- name: Docker push
    #  run: |
    #    docker push ghcr.io/srivatsamarichi/piggymetrics-turbine-stream-service:${{ github.run_number }}
